// @ts-check
/**
 * Shared flat ESLint config that ENFORCES docs/GUIDELINES.md, not just style:
 *  - file/function size guard-rails (§8)
 *  - feature isolation via eslint-plugin-boundaries (§2)
 *  - accessibility (§4) and the no-danger XSS guard (§12.3)
 *
 * Consumers import the preset they need and append project-specific bits:
 *   import { react, featureBoundaries } from '@convex-tanstack-starter/eslint-config';
 *   export default [...react, featureBoundaries(), { ignores: [...] }];
 */
import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import reactPlugin from 'eslint-plugin-react';
import reactHooks from 'eslint-plugin-react-hooks';
import jsxA11y from 'eslint-plugin-jsx-a11y';
import boundaries from 'eslint-plugin-boundaries';
import globals from 'globals';

/** Files generated by tooling that must never be linted. */
export const ignores = {
  ignores: [
    '**/dist/**',
    '**/.output/**',
    '**/.vinxi/**',
    '**/.tanstack/**',
    '**/.turbo/**',
    '**/coverage/**',
    '**/convex/_generated/**',
    '**/routeTree.gen.ts',
  ],
};

/** TypeScript baseline + the size/quality rules from GUIDELINES §8. */
export const base = tseslint.config(js.configs.recommended, ...tseslint.configs.recommended, {
  languageOptions: {
    ecmaVersion: 2023,
    sourceType: 'module',
    globals: { ...globals.node },
  },
  rules: {
    // §8 — size is a single-responsibility smell, not a vanity metric.
    'max-lines': ['error', { max: 500, skipBlankLines: true, skipComments: true }],
    'max-lines-per-function': [
      'warn',
      { max: 80, skipBlankLines: true, skipComments: true, IIFEs: true },
    ],
    complexity: ['warn', 12],
    // §4 — no `any`, prefer explicit unused markers.
    '@typescript-eslint/no-explicit-any': 'error',
    '@typescript-eslint/no-unused-vars': [
      'error',
      { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' },
    ],
    '@typescript-eslint/consistent-type-imports': [
      'error',
      { prefer: 'type-imports', fixStyle: 'separate-type-imports' },
    ],
    'no-console': ['warn', { allow: ['warn', 'error'] }],
  },
});

/** React app preset: base + React, hooks, a11y, and the no-danger XSS guard. */
export const react = tseslint.config(
  ...base,
  reactPlugin.configs.flat.recommended,
  reactPlugin.configs.flat['jsx-runtime'],
  jsxA11y.flatConfigs.recommended,
  {
    plugins: { 'react-hooks': reactHooks },
    languageOptions: {
      globals: { ...globals.browser },
    },
    settings: { react: { version: 'detect' } },
    rules: {
      'react-hooks/rules-of-hooks': 'error',
      'react-hooks/exhaustive-deps': 'warn',
      // §12.3 — dangerouslySetInnerHTML is banned by default; require DOMPurify when truly needed.
      'react/no-danger': 'error',
      'react/prop-types': 'off',
      'react/react-in-jsx-scope': 'off',
    },
  },
);

/**
 * Feature-isolation rules (§2). Enforces:
 *  - a feature may import another feature ONLY through its public `index.ts`;
 *  - routes/shared may not reach into feature internals;
 *  - shared code never depends on a feature.
 * Tuned to the `<appDir>/src/features/<feature>/...` layout. `appDir` is the
 * app path relative to the directory ESLint runs from (the monorepo root here).
 */
export function featureBoundaries({ appDir = 'apps/web' } = {}) {
  const root = `${appDir}/src`;
  return {
    files: [`${root}/**/*.{ts,tsx}`],
    plugins: { boundaries },
    settings: {
      // Resolve the `#/*` alias and workspace packages so boundaries can
      // classify imports by their real file path.
      'import/resolver': {
        typescript: { project: `${appDir}/tsconfig.json` },
        node: true,
      },
      'boundaries/include': [`${root}/**/*`],
      'boundaries/elements': [
        // Order matters: most specific first.
        {
          type: 'feature-public',
          pattern: `${root}/features/*/index.{ts,tsx}`,
          mode: 'full',
          capture: ['feature'],
        },
        {
          type: 'feature-internal',
          pattern: `${root}/features/*/**`,
          mode: 'full',
          capture: ['feature'],
        },
        { type: 'route', pattern: `${root}/routes/**` },
        { type: 'shared', pattern: `${root}/{lib,components,hooks,styles,integrations}/**` },
        { type: 'app-root', pattern: `${root}/{router,ssr,client,routeTree.gen}.{ts,tsx}` },
      ],
    },
    rules: {
      'boundaries/no-unknown': 'off',
      'boundaries/no-unknown-files': 'off',
      'boundaries/element-types': [
        'error',
        {
          default: 'disallow',
          message:
            '${file.type} is not allowed to import ${dependency.type} (docs/GUIDELINES.md §2 feature isolation).',
          rules: [
            {
              from: ['feature-internal'],
              allow: [
                ['feature-internal', { feature: '${from.feature}' }],
                ['feature-public', { feature: '${from.feature}' }],
                'feature-public',
                'shared',
              ],
            },
            {
              from: ['feature-public'],
              allow: [
                ['feature-internal', { feature: '${from.feature}' }],
                'feature-public',
                'shared',
              ],
            },
            { from: ['route'], allow: ['feature-public', 'shared', 'app-root'] },
            { from: ['shared'], allow: ['shared'] },
            { from: ['app-root'], allow: ['feature-public', 'shared', 'route', 'app-root'] },
          ],
        },
      ],
    },
  };
}
